[
    {
        "domain": ".facebook.com",
        "expirationDate": 1787474203.994566,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_l",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787759735.766365,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eFV7aLFW9PByShIJ8YNacdVa"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1760975793.774052,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0aEp4Lgp3YiLX1M5E.AWcC2tcHF3Hf94S08tGvtyd6LhNMGC_rKARyNWv_sec5Wg5sLGM.Boe1V5..AAA.0.0.Bof7Sx.AWfM8ssefDqVCMsgq6w3ObOhj7E"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1758383795,
        "hostOnly": false,
        "httpOnly": false,
        "name": "vpd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v1%3B620x360x3"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1784565396.044332,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "25%3AyQRvztlxtCEMkA%3A2%3A1753029396%3A-1%3A-1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1784735795,
        "hostOnly": false,
        "httpOnly": false,
        "name": "fbl_st",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "100427516%3BT%3A29219996"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1753634199.124084,
        "hostOnly": false,
        "httpOnly": false,
        "name": "locale",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "en_GB"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "m_pixel_ratio",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "3"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1784565396.04348,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "61553825343191"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787759793.774356,
        "hostOnly": false,
        "httpOnly": true,
        "name": "pas",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "61578624325695%3AZ35IfPSTpd%2C61553825343191%3A7tV4b2OF8o"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787474203.994879,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787589396.044128,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "eVV7aBgshmys889DP0vrP_NT"
    },
    {
        "domain": ".facebook.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "360x803"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1760975795,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wl_cbv",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "v2%3Bclient_version%3A2877%3Btimestamp%3A1753199794"
    }
]
